#' Visualize orbital trajectories in 2D
#'
#' Generates a 2D top-down projection of the orbital paths using `ggplot2`.
#' This function traces the historical trajectory of each body and places a solid
#' point at its final computed position. It automatically enforces a 1:1 aspect ratio
#' (`coord_equal`) to ensure that circular orbits are visually accurate and not distorted.
#'
#' @param sim_data A tidy `tibble` containing the physical state data (time, x, y, id)
#'   generated by the `simulate()` function.
#'
#' @return A `ggplot` object representing the trajectory map.
#' @export
#'
#' @examples
#' \dontrun{
#' # Build, simulate, and plot a 28-day Earth-Moon system
#' orbit_data <- create_system() |>
#'   add_body(id = "Earth", mass = 5.97e24) |>
#'   add_body(id = "Moon", mass = 7.34e22, x = 3.84e8, vy = 1022) |>
#'   simulate(time_step = 3600, duration = 86400 * 28)
#'
#' plot_orbits(orbit_data)
#' }
plot_orbits <- function(sim_data) {
  ggplot2::ggplot(sim_data, ggplot2::aes(x = x, y = y, color = id)) +
    ggplot2::geom_path(linewidth = 1, alpha = 0.8) +
    # Put a solid dot at the final position
    ggplot2::geom_point(data = dplyr::filter(sim_data, time == max(time)), size = 4) +
    ggplot2::theme_minimal() +
    ggplot2::labs(title = "orbitr: Trajectory Map", x = "X Position (m)", y = "Y Position (m)", color = "Body") +
    ggplot2::coord_equal() # Forces 1:1 aspect ratio
}
